application: bitcoin-p
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
handlers:
- url: /fetchrates
  script: ratefetch.app
  login: admin
- url: /.*
  script: api.app
libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: latest
